config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :reservations

  devise_for :users, controllers: { registrations: "registrations" }

  root "home#index"
  get 'contact', to: 'contact_form#new'
  post 'contact', to: 'contact_form#create'

  get "home/reservations", as: "reservations_history"
  get "home/reservations_current", as: "reservations_current"
  get 'get_parking_spots', to: 'reservations#get_parking_spots'
  delete 'reservations/:id', to: 'reservations#destroy', as: 'delete_reservation'
  get 'reservations/:id/activate', to: 'reservations#activate', as: 'activate_reservation'
  get 'home/search', as: "search_reservations"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  def reservations
    @reservations = current_user.reservations
  end
  def reservations_current
    @reservations = current_user.reservations
  end
  def contact
    @contact_form = ContactForm.new
  end
  
  def create_message
    @contact_form = ContactForm.new(contact_params)
    
    if @contact_form.valid?
      ContactMailer.contact_email(@contact_form).deliver_now
      
      flash[:notice] = "Wiadomość została wysłana!"
      redirect_to root_path
    else
      flash[:alert] = "Nie udało się wysłać wiadomości. Sprawdź poprawność wprowadzonych danych."
      render :contact
    end
  end
  def search
    @reservations = Reservation.joins(:user)
    if params[:license_plate].present?
      @reservations = @reservations.where("LOWER(reservations.license_plate) LIKE ?", "%#{params[:license_plate].downcase}%")
    end
    if params[:first_name].present?
      @reservations = @reservations.where("LOWER(users.first_name) LIKE ?", "%#{params[:first_name].downcase}%")
    end
    if params[:last_name].present?
      @reservations = @reservations.where("LOWER(users.last_name) LIKE ?", "%#{params[:last_name].downcase}%")
    end
    if params[:phone].present?
      @reservations = @reservations.where("LOWER(users.phone) LIKE ?", "%#{params[:phone].downcase}%")
    end
    @reservations = @reservations.order(created_at: :desc)

    params[:license_plate] = nil
    params[:first_name] = nil
    params[:last_name] = nil
    params[:phone] = nil
  
    render :search
  end
  
  private
  
  def contact_params
    params.require(:contact_form).permit(:name, :email, :message)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container" style="padding-top:10%"> 
  <div class="row">
    <div class="col-lg-4">
        <div class="d-grid gap-3 employee-info">
      <h2 class="text-center  p-2 rounded-pill" style="border-bottom: 1px solid black">Mapa parkingu</h2>
        <a href="parking_map.jpg" target="_blank">
          <img src="parking_map.jpg" alt="Parking" class="img-fluid float-right" style="border-radius: 5%;border: 1px grey groove;">
        </a>
        </div>
    </div>
    <div class="col-lg-4 bg-secondary rounded">
      <br>
      <div class="d-grid gap-3">
      <% if current_user&.employee? %>
        <h2 class="text-center text-white p-2 rounded" style="border-bottom: 1px solid white">Dostępne opcje</h2>
          <%= link_to "Wykonaj rezerwację w imieniu", new_reservation_path, class: "btn btn-primary btn-block mb-3" %>
          <%= link_to "Szukaj rezerwacji", search_reservations_path, class: "btn btn-primary btn-block mb-3" %>
        <h2 class="text-center text-white p-2 rounded" style="border-bottom: 1px solid white"> </h2>
        <% elsif current_user&.client? %>
          <%= link_to "Wykonaj rezerwację", new_reservation_path, class: "btn btn-primary btn-block mb-3" %>
          <%= link_to "Rezerwacje parkingowe", reservations_current_path, class: "btn btn-primary btn-block mb-3" %>
          <%= link_to "Historia rezerwacji parkingowej", reservations_history_path, class: "btn btn-primary btn-block mb-3" %>
        <% else %>
          <h2 class="text-center text-white p-2 rounded">Musisz być zalogowany!</h2>
          <%= link_to "Zaloguj się", new_user_session_path, class: "btn btn-primary btn-block mb-3" %>
        <% end %>
      </div>
    </div>
<div class="col-lg-4">
  <% if current_user&.employee? %>
    <div class="d-grid gap-3 employee-info">
      <h2 class="text-center text-black p-2 rounded-pill" style="border-bottom: 1px solid black">Informacje o pracowniku</h2>
      <% employee_data = current_user %>
      <p>Imię: <%= employee_data.first_name %> </p>
            <p>Nazwisko: <%= employee_data.last_name %> </p>
                        <p>Telefon: <%= employee_data.phone %> </p>

      <% for reservation in current_user.reservations %>
        <p>Przypisane miejsce parkingowe: <%= reservation.parking_spot.name %> </p>
        <p> Region parkingowy: <%=reservation.parking_spot.region.name.split()[1]%> </p>
      <% end %>
    </div>
    <% elsif current_user&.client? %>
        <div class="d-grid gap-3 employee-info">
      <h2 class="text-center text-black p-2 rounded-pill" style="border-bottom: 1px solid black">Twoje informacje</h2>
      <% client_data = current_user %>
      <p>Imię: <%= client_data.first_name %> </p>
            <p>Nazwisko: <%= client_data.last_name %> </p>
                        <p>Telefon: <%= client_data.phone %> </p>
    </div>
  <% end %>
</div>

    </div>
  </div>
</div>

app/views/home/reservations.html.erb
<div class="container">
<% if @reservations.any? %>
  <div class="card text-white mx-auto" > 
  <div class="card-header">
        <h4 class="card-title" style="color:black">Historia  rezerwacji</h4>
</div>
    <div class="card-body">
      <h4 class="card-title" style="color:black">Historia Twoich rezerwacji</h4>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Rejon</th>
            <th>Miejsce parkingowe</th>
            <th>Data</th>
            <th>Godzina</th>
            <th>Czas trwania</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @reservations.each do |reservation| %>
            <% if reservation.reservation_date < Date.today %>
              <tr>
                <td><%= reservation.parking_spot.region.name  %></td>
                <td><%= reservation.parking_spot.name  %></td>
                <td><%= reservation.reservation_date.strftime("%d-%m-%Y") %></td>
                <td><%= reservation.reservation_time.strftime('%H:%M') %></td>
                <td><%= reservation.duration %> min</td>
                <td>Zakończone</td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
<div class="container d-flex align-items-center justify-content-center" style="height: 100vh;">
  <div class="bg-white p-4">
    <p class="text-center">Twoja historia rezerwacji jest pusta.</p>
  </div>
</div>

<% end %>
</div>

app/views/home/reservations_current.html.erb
<div class="container">
<% if @reservations.any? %>
  <div class="card text-white mx-auto" > 
  <div class="card-header">
        <h4 class="card-title" style="color:black">Historia rezerwacji</h4>
</div>
    <div class="card-body">
      <h4 class="card-title" style="color:black">Twoje rezerwacje</h4>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Miejsce parkingowe</th>
            <th>Data</th>
            <th>Godzina</th>
            <th>Czas trwania</th>
            <th>Status</th>
            <th>Edycja</th>
            <th>Anulowanie</th>
            <th>Płatność </th>
          </tr>
        </thead>
        <tbody>
          <% @reservations.each do |reservation| %>
            <% if reservation.reservation_date >= Date.today %>
              <tr>
                <td><%= reservation.parking_spot.name %></td>
                <td><%= reservation.reservation_date.strftime("%d-%m-%Y") %></td>
                <td><%= reservation.reservation_time.strftime('%H:%M') %></td>
                <td><%= reservation.duration %></td>
                <td> <%= reservation.status %></td>
                <td>
                  <%= link_to "Edytuj", edit_reservation_path(reservation.id), class:"btn btn-primary"%>
                </td>
                <td>
                  <%= button_to "Anuluj", delete_reservation_path(reservation.id), class:"btn btn-danger", method: :delete %>
                </td>
                <td> 
                <% if reservation.status == "accepted" %>
                <label for="payment_method">Metoda płatności:</label>
                
                  <select id="payment_method" name="payment_method">
                    <option value="blik">BLIK</option>
                    <option value="card">Karta</option>
                    <option value="transfer">Przelew</option>
                    <option value="cash">Gotówka w portierni</option>
                  </select>
                  <br/>
                   <%= link_to "Opłać", edit_reservation_path(reservation.id), class:"btn btn-primary"%>
                <% else %>
                <p> Niedostępne <p>
                <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
<div class="container d-flex align-items-center justify-content-center" style="height: 100vh;">
  <div class="bg-white p-4">
    <p class="text-center">Brak rezerwacji do wyświetlenia.</p>
  </div>
</div>

<% end %>
</div>

app/views/home/search.html.erb
<div class="container">
<br/><br/><br/>
<h1> Wyszukaj rezerwacje </h1>
<%= form_tag search_reservations_path, method: :get do %>
  <div class="form-group">
    <%= label_tag :first_name, "Imię osoby rezerwującej" %>
    <%= text_field_tag :first_name, params[:first_name], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :last_name, "Nazwisko osoby rezerwującej" %>
    <%= text_field_tag :last_name, params[:last_name], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :phone, "Numer telefonu osoby rezerwującej" %>
    <%= text_field_tag :phone, params[:first_name], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :license_plate, "Numer tablicy rejestracyjnej osoby rezerwującej" %>
    <%= text_field_tag :license_plate, params[:license_plate], class: "form-control" %>
  </div>
<br/>
  <%= submit_tag "Szukaj", class: "btn btn-secondary" %>
<% end %>
<% if @reservations.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Imię</th>
        <th>Nazwisko</th>
        <th>Numer tablicy rejestracyjnej</th>
        <th>Miejsce parkingowe</th>
        <th>Data </th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= reservation.user.first_name %></td>
          <td><%= reservation.user.last_name %></td>
          <td><%= reservation.license_plate %></td>
          <td><%= reservation.parking_spot.name %></td>
          <td><%= reservation.reservation_date.strftime("%d-%m-%Y") %></td>
          <td><%= reservation.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No reservations found.</p>
<% end %>
</div>