config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :reservations

  devise_for :users, controllers: { registrations: "registrations" }

  root "home#index"
  get 'contact', to: 'contact_form#new'
  post 'contact', to: 'contact_form#create'

  get "home/reservations", as: "reservations_history"
  get "home/reservations_current", as: "reservations_current"
  get 'get_parking_spots', to: 'reservations#get_parking_spots'
  delete 'reservations/:id', to: 'reservations#destroy', as: 'delete_reservation'
  get 'reservations/:id/activate', to: 'reservations#activate', as: 'activate_reservation'
  get 'home/search', as: "search_reservations"
end

app/views/nav/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <%= link_to "Parking Management System", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user&.client? %>
            <li class="nav-item">
              <%= link_to "Zarezerwuj miejsce parkingowe", new_reservation_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Twoje rezerwacje", reservations_current_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Historia rezerwacji parkingowej", reservations_history_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Kontakt", contact_path, class: "nav-link" %>
            </li>
        <% elsif current_user&.employee?%>
          <%= link_to "Wykonaj rezerwację w imieniu", new_reservation_path, class: "nav-link" %>
          <%= link_to "Szukaj rezerwacji", search_reservations_path, class: "nav-link" %>

        <% end %>
      </ul>
      <div class="d-flex align-items-center">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "Ustawienia konta", edit_user_registration_path, class: "nav-link btn btn-link" %>
            </li>
            <li class="nav-item">
              <%= button_to "Wyloguj się", destroy_user_session_path, method: :delete, class: "nav-link btn btn-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Zaloguj się", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Zarejestruj się", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>